services:
  tailscale:
    image: tailscale/tailscale:v1.94.2
    container_name: tailscale
    hostname: tailscale-container
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale:/var/lib/tailscale
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS}
      TS_STATE_DIR: ${TS_STATE_DIR}
    network_mode: host
    restart: unless-stopped
